# 2023瀧川ゼミ計算社会科学ハンズオンセミナー1

## Pythonの基本の基本
- このパートではPythonの基本の基本を勉強します。
- まずPythonでの数値と演算について説明します。


### 数値と演算
- Pythonの演算子を表にまとめました。累乗```**```、整数の割り算```//```の記法には注意。

|  演算子  | 演算  |
| ---- | ---- |
| **  |  累乗  |
|  * | 掛け算  |
|  / | 割り算  |
|//|整数の割り算|
|%|剰余（割り算のあまり）|
|+|足し算|
|-|引き算|



```{admonition} 各種計算
以下では各種の計算をします。
```

In [5]:
10 // 3

3

In [6]:
10 % 3

1

In [ ]:
2 / 5

0.4

In [ ]:
5 / 2

2.5

In [ ]:
5 % 2

1

```{caution} 
演算の順番には気をつけましょう。
```


In [ ]:
 5 ** 2 + 4 * 3 + (-2) * 3#演算の順番に注意

31

```{important}
- 剰余計算%はプログラミングでは頻出。
- 演算の順番に注意。
- #を使うとコメントを書けます。
```

### 数値の型
- Pythonのオブジェクトにはすべて型（type）があります。
- ここでは大きく分けて数値型というtypeを扱っています。
- 数値型のなかでもさらに下記のようないくつかのtypeが分かれます。
    - int 整数型
    - float 浮動小数点型

```{caution}
- 文字列strと混同しないこと
- intやfloatで文字列をそれぞれの型に型変換できる
```

In [ ]:
type(5)

int

In [ ]:
type(5.0)

float

In [ ]:
1/3

0.3333333333333333

```{tips}
""で囲むと文字列になります。
```

In [ ]:
"3"

'3'

```{caution}
異なる型同士の```+```演算はできません。
```

In [ ]:
9 + "3"

TypeError: ignored

floatをintに変換します。

In [ ]:
int(5.0)

5

intをfloatに変換します。

In [ ]:
float(5)

5.0

In [ ]:
int('5') + 10

15

### 変数
- 変数とは、値を入れておく箱のようなものです。
- 代入の演算子は、```=```を使います。
  - 数学の等号とは異なるので注意。比較演算子（後述）では"=="を使う。
- 同じ変数に別の値を代入すると、変数の中身が更新されます。


In [ ]:
a = 5
b = 2
a/b

2.5

- ```a```に```4```を代入すると、計算の結果が変わります。

In [ ]:
a = 4
a/b

2.0

### 累積代入文
- プログラミングでは、ある変数の値にさらに別の値を加えたりすることがあります。


In [ ]:
a = 3
a = a - 3
a

0

- 以下のような書き方を出来ます。

In [ ]:
a = 3
a += 3
a

6

### 関数

- 関数は引数（インプット）を与えると返り値（アウトプット）を返すはたらきをします。
  - （数学の関数と違って）どちらか、ないし両方なくてもよい。
- Pythonではdefを使って関数を定義できます。


In [1]:
def myfunc(a, b):
  c = a**2 + b
  return c


In [2]:
myfunc(4,2)

18

### 変数のスコープ
- 変数にはそれが機能する空間（名前空間）が決まっています。
- 関数の中で定義した変数はその関数の中でしか定義どおりにはふるまいません。

- 例えば、以下のように関数の外で```b = 10```として...

In [6]:
b = 10
def myfunc2(arg):
    b = 10*arg
    print(b)

関数の中では```b=100```となっているが…

In [7]:
myfunc2(b)

100


外では```10```のままである。

In [8]:
b

10

#### グローバル変数とローカル変数
- どこでも（グローバルに）通用する変数を作りたい場合は```global```を用いる。
- グローバル変数はどの空間でも同じようにふるまいます。
- これに対して、関数の中で定義された変数をローカル変数といいます。

In [20]:

b = 10
def myfunc3(arg):
    global c
    c = b + arg
    print(c)


In [21]:
myfunc3(30)

40


In [22]:
c

40

### ブール型
- Pythonには数値型以外に文字列型、リスト型などのデータ型がありますが、まずここではブール型という型のオブジェクトを紹介します。
- これはTrueかFalseの二値をとるデータ型です。


In [ ]:
b = True

In [ ]:
b

True

  - notで否定すると```False```となります。```not```は論理演算子（後述）の一種です。


In [ ]:
not b

False

### if文とブール型
- プログラミングには制御文といって、プログラミングのフローを制御する文があります。
- if文はある条件のときに、〜せよ、といったタイプの制御文です。
- if文の条件はブール型を返す文で書きます。つまり、ある条件がTrueなら以下を実行せよ、という命令となります。


In [10]:
if b:
    print('実行')

実行


In [11]:
if not b:
    print('実行')

### 比較演算子、論理演算子
- if文の条件などを作るときに、比較したり、否定の条件を使うことが多いです。
- このような演算は、比較演算子と論理演算子で行われ、演算の結果ブール型が生み出されます。


- 論理演算子

| 演算子| 意味 |
|:-----------:|:------------:|
|a and b| aかつb|
|a or b| aあるいはb|
|not a|aでない |

- 比較演算子

| 演算子| 意味 |
|:-----------:|:------------:|
|a == b|	bがaに等しい|
|a != b|	bがaに等しくない|
|	a > b|	bよりaが大きい|
|	a >= b|	bよりaが大きいか等しい|
|	a < b	|bよりaが小さい|
|	a <= b|	bよりaが小さいか等しい|



- 以下で例をみていきます。

In [ ]:
a = True
b = True
not (a or b)

False

In [ ]:
a = 3; b = 5
a == 3

True

In [ ]:
b != 5

False

In [ ]:
a > b

False

In [ ]:
a + 2 >= b

True

In [ ]:
a + 2 >= b and b != 5

False

## 問題１

### 例題
- 変数xとyが与えられています。xが偶数で、yが奇数の場合に真(True)を返す論理式を作成してください。

In [ ]:
x = 8
y = 14

(x % 2 == 0) and (y % 2 == 1)


False

### 問題1-1
- 与えられた整数xが、3の倍数でもあり、かつ4で割り切れるかどうかを判定する論理式を作成してください。

In [ ]:
x = 16
(x % 3 == 0) and (x % 4 == 0)

False

### 問題1-2
- 与えられた2つの整数mとnが、どちらも5で割り切れる場合にTrueを返し、そうでない場合はFalseを返す論理式を作成してください。



In [ ]:
m = 10
n = 15
(m % 5 == 0) and (n % 5 == 0)

True

### 問題1-3
- 与えられた整数pが、10未満かつ偶数であるか、または20以上かつ奇数である場合に真(True)を返す論理式を作成してください。

In [ ]:

p < 10 and p % 2 == 0 and p % 2 == 1 and p >= 20 

False

## 制御文
- プログラミングでは、しばしば命令の流れを条件分岐したり繰り返したりして制御する必要がある。
- 条件分岐はif、ループはforを用いる。whileは条件付きのループである。

### if文とブロックの書き方。
- if文で条件分岐をする。
- if の後に条件を書き、:で改行し、ブロック部分を書く。
- elseはif以下の条件を満たさないときに実行される。


In [ ]:
# 6がtにあれば、"in"なければ"out"を出力する。
t=[1,2,3,4,5]
if 3 not in t: 
    print ("in")
else:
    print ("out")

out


```{important}
- 3つ以上条件があるときはelifを使う。
```

In [ ]:
# xが2で割り切れれば'A',3で割り切れれば'B'、どちらでもなければ'C'を返す。
def myfunc(x):
  if x % 2 == 0: 
    print("A")
  elif x % 3 == 0:
    print("B")
  else:
    print("C")
myfunc(7)

C


```{note}
- []はリスト型（後述）
- x in y はxがyに含まれればTrue、そうでなければFalseを返す。
```

### if文による簡単なプログラム
- 例えば、簡単なクイズを出して、正解／不正解を返すプログラムを作ることができる。


In [ ]:
var = input('マックスの誕生年はいつでしょう？')
var = int(var)
if var == 1864:
    print('正解です！')
else:
    print('不正解です。。')

マックスの誕生年はいつでしょう？1863
不正解です。。


```{tip}
- input()関数で入力フォームに記入した文字列をプログラムに組み込むことが可能。


### for文
- 同じ処理を繰り返し行いたい（ループさせたい）とき、for文を使う。
- for i in XでXの要素を一つずつi回ループする。
- range()は連続する数値からなるデータを返す。


In [ ]:
for i in range(1,6):
  print (i)

1
2
3
4
5


```{important}
- リストなどの要素をループさせることも可能。


In [ ]:
t=['a','b','c','d','e']
for i in t:
    print (i)

a
b
c
d
e


```{tip}
- 単にループだけさせたいときは、_ in range()と書くことも可能

In [ ]:
for _ in range(10):
  print('Hello')

Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello


### continue とbreak
- プログラムを実行中に、ループを途中で抜けたり、終わらせたりする命令として```continue```と```break```があります。
- ```continue```は以後の処理をとばして次の処理へいくのに対して、```break```はループ自体を終了する。


In [ ]:
for item in t:
    if item=='c':
        continue
    print (item)

a
b
d
e


In [ ]:
for item in t:
    if item!='c':
        print (item)
    else:
        break

a
b


### while文
- while文は条件を満たす限り、ブロックの実行を繰り返す。


In [ ]:
t = 1
while t != 6:
    print (t)
    t += 1
    #t = t +1

1
2
3
4
5


- while Trueで無限ループを作ることができる。

In [ ]:
t = 1
while True:
    print (t)
    t += 1
    if t == 6:
      break

1
2
3
4
5


```{note}}
- 無限ループは、ある処理をループして条件を満たしたときに終わらせる。プログラミングでは頻出します。

In [ ]:
a = 2
b = 4
c = a + b
print(c)

6


## 問題2 



### 問題2-1

- 1から10までの整数のリストから、偶数だけを表示してください。

In [ ]:
t = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
t = range(1,11)#こっちでもよい

In [ ]:
for i in t:
  if i % 2 == 0:
    print(i)

### 問題2-2
- 与えられたリスト[1, 3, 9, 16, 20, 25, 28, 30]の要素に対して、次の条件に従って処理を行ってください。

  - 偶数の場合は2で割る。
  - 奇数の場合は2倍する。

In [ ]:
t = [1, 3, 9, 16, 20, 25, 28, 30]


In [ ]:
for i in t:
  if i % 2 == 0:
    print(i//2)
  else:
    print(i*2)


 ### 問題2-3
- 与えられた整数nに対して、1からnまでのすべての奇数の合計を計算してください（continueを使うこと）。

In [ ]:
sum = 0
n = 300

for i in range(1, n + 1):
  if i % 2 == 0:
    continue
  sum += i

print(sum)

22500


## ユークリッドの互除法
- ここで、プログラミングらしい課題としてユークリッドの互除法というアルゴリズムの実装にトライしてみましょう。
-  ユークリッドの互除法とは、2つの整数、aとbの最大公約数を求めるアルゴリズムです。例えば、2485と1162の最大公約数を求めたい場合

$2485 \div1162 = 2 余り 161$ 

$1162 \div 161 = 7 余り 35$ 

$161 \div 35 = 4 余り 21$ 

$35 \div 21 = 1 余り 14$

$21 \div 14 = 1 余り 7$

$14 \div 7 = 2 余り 0$

割る数と余りを次回の割られる数と割る数にして、次々と計算し、最後に割り切れたら終わりで、最後の割る数が最大公約数です。



## 問題3
### 例題
- ユークリッドの互除法をPythonで実装しましょう。ヒントwhileを用います。余りがゼロでないならば、〜を実行せよ、という形式をとります。また、余りを計算するには%演算子を使います。

In [ ]:
#答え
a = 2485
b = 1162
while b !=0:
    r = a % b#入れ替え用のrを用意する 
    a = b
    b = r
    print(a,b)


1162 161
161 35
35 21
21 14
14 7
7 0


In [ ]:
#別解
a = 2485
b = 1162
while b !=0:
    a, b = b, a % b#この書き方で複数の変数に代入できて、入れ替え用を用意する必要もない。 
    print(a,b)


1162 161
161 35
35 21
21 14
14 7
7 0


### 問題 3-1
与えられた整数nに対して、nの階乗（n!）を求める関数factorialを定義してください。ただし、0の階乗は1と定義します。

In [ ]:
def factorial(n):
    if n == 0:
        return 1
    else:
        result = 1
        for i in range(1, n+1):
            result *= i
        return result



In [ ]:
# 例: 5の階乗を計算
result = factorial(5)
result

120

### 問題3-2
与えられた整数nが素数かどうかを判定する関数is_primeを作成してください。



In [ ]:
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

n = 17
result = is_prime(n)


In [ ]:
is_prime(23095832905823409587)


False

### 問題3-3
フィボナッチ数列の要素を生成し続けます。要素が1000を超えるような最初のフィボナッチ数を求めてください。
$$F_0 = 0$$
$$F_1 = 1$$
$$F_{n+2} = F_n + F_{n+1} (n ≥ 0)$$

In [ ]:
def first_fib_over_n(n):
    a, b = 0, 1
    while True:
        a, b = b, a + b
        if b > n:
            break
    return b

n = 1000
result = first_fib_over_n(n)


In [ ]:
result

1597

## データ型
- Pythonはオブジェクト指向のプログラミング言語であり、変数、関数をはじめとしたプログラムの部品はすべてオブジェクトである。
- オブジェクトはデータともいわれ、ある型を持っている（すでに数値に型があることは説明した）。
- 以下では、特に重要なデータ型として、文字列、リスト、ディクショナリ、タプルについて解説する。

## 文字列
- 文字列は数値とは異なるデータ型の一つで、文字通り文字を扱います。
- ""ないし''でくくると文字列になります。


In [ ]:
text = "Hello!"
text

'Hello!'

```{important}
- 文字列は、シークエンス型という広義の型に属していて、インデックスで要素を指定して取り出すことができる。

In [ ]:
text[3]

'l'

```{admonition} インデックスとメソッド
- これから文字列の操作をするメソッドなどについて解説していきますが、その前にインデックスとメソッドの概念について紹介します。
- この話題は文字列に限られるものではなく、インデックスはシークエンス型一般に、メソッドはデータ型一般に適用される概念です。


## インデックス

- Pythonのインデックスは0から始まる。
- ":"それ以後を続けてとる。
- "-"は後ろから数える。
- <img src="https://raw.githubusercontent.com/berutaki/github.io/main/1-4.png" width="500">


In [ ]:
text[0:3]

'Hel'

In [ ]:
text[1:]

'ello!'

In [ ]:
text[-1]

'!'

```{error}
- リスト型では、数字を飛ばしてインデックスを指定できません！


In [ ]:
text[[2,4]]

TypeError: ignored

```{important}
- numpyというライブラリのarrayという型を使えば可能です。（→後述）

## メソッド
- データ型にはそれぞれに固有の関数のようなものがあります。これをメソッドといいます。
- メソッドは、それぞれのデータ型をもつオブジェクトに対して何らかの操作をします。
- メソッドはhoge.XXXX()という形を取ります。

In [ ]:
text.replace('ll','oo')

'Heooo!'

```{error}
- データ型によって使えるメソッドが決まっています。

- 例えば、replace()は文字型のメソッドで数値型には使えません。

In [ ]:
a = 3943
a.replace(3,4)

AttributeError: ignored

### 文字列操作
- 文字列を操作するメソッドはさまざまです。ここでは特に使用頻度の高いものをピックアップして紹介します。
```{list-table}
:header-rows: 1
* - 機能
  - メソッド
* - 結合
  - join()
* - 置換
  - replace()
* - 検索
  - find()
* - 分割
  - split()
* - クリーニング
  - strip()
* - 頭文字、最後の文字
  - startswith(), endwith()
```


#### 結合、```+```、join()メソッド
- '+'で結合できる。
- リストの結合はjoin()を使う。

In [ ]:
a = "Hello!"
b = "こんにちは!"

In [ ]:
a+b

'Hello!こんにちは!'

In [ ]:
strings = ["Hello!","こんにちは!"]

In [ ]:
''.join(strings)

'Hello!こんにちは!'

In [ ]:
','.join(strings)

'Hello!,こんにちは!'

#### 置換、replace()メソッド
- 部分文字列を別の部分文字列に置換するには、replace()メソッドを使います。

In [ ]:
a = "私の名前は、マックスです。"

In [ ]:
a.replace("マックス","エミール")

'私の名前は、エミールです。'

#### 小文字化、lower()メソッド
- 文字通り小文字化するメソッドです。upper()は大文字化します。

In [ ]:
a = "Hello!"
a.lower()

'hello!'

In [ ]:
a.upper()

'HELLO!'

 #### 検索、find()メソッド
- find()メソッドはその部分文字列の始まるインデックスを返す。。なければ-1を返す。
- 含まれるかどうかはinを使う方がわかりやすい。

In [ ]:
a = "私の名前は、マックスです。"

In [ ]:
a.find("マックス")

6

In [ ]:
a.find("ゲオルグ")

-1

In [ ]:
"マックス" in a

True

#### 分割、split()メソッド
- 文字列を分割したい場合はsplit()メソッドを使います。引数には、分割したい箇所にある文字列、例えば'、'を与えます。ただし、その文字列は失われます。

In [ ]:
a.split('、')

['私の名前は', 'マックスです。']

In [ ]:
a

'私の名前は、マックスです。'

#### クリーニング、strip()メソッド

- とくにテクストデータを外部から読み込んできた場合など、前後に空白や改行マーク"\n"がついてくることがあります。これを取り除くにはstrip()メソッドを使います。

In [ ]:
b = " マックス・ウェーバー\n"

In [ ]:
b

' マックス・ウェーバー\n'

In [ ]:
b.strip()

'マックス・ウェーバー'

#### startswith(), endwith()メソッド
- ある部分文字列から始まる、あるいは終わるかを調べるには、startswith(), endwith()を使います。

In [ ]:
'マックス・ウェーバー'.startswith('マックス')

True

In [ ]:
'マックス・ウェーバー'.endswith('ズ')

False

#### フォーマット
- 文字列の中に変数の値を埋め込みたいことがよくあります。
- pythonではf'hoge{}'とすると変数の値を埋め込むことができます。


In [ ]:
a = 'マックス'
b = 'ウェーバー'
f'私の名前は{a}・{b}です'

'私の名前はマックス・ウェーバーです'

```{note}
- 別の書き方としてformat()メソッドを使う方法がありますが、最初の方法の方がわかりやすいでしょう。

In [ ]:
'私の名前は{}・{}です'.format(a,b)

'私の名前はマックス・ウェーバーです'

```{note}
- 他に、%演算子を使う方法があります。この場合%s(文字列)のようにデータ型を指定します。
- これはC言語などで用いられる古典的な文法です。

In [ ]:

'私の名前は%s・%sです'%(a,b)

'私の名前はマックス・ウェーバーです'

## リスト
- リストも文字列と同様、シークエンス型です。
- []でくくって、作ります。


In [ ]:
a = [1,2,3,4,5]
a

[1, 2, 3, 4, 5]

In [ ]:
b = ["Apple","Banana"]
b

['Apple', 'Banana']

```{important}
リストには、どんなデータ型でも入れられるし、同じリストに異なるデータ型を入れることもできます。

In [ ]:
c = [1,2,3,4,5,"Apple","Banana"]
c

[1, 2, 3, 4, 5, 'Apple', 'Banana']

```{important}
- さらにリストの特徴としてネストすることができます。つまり、リストのなかにリストをもつことができます。また、リストのリストのリストなどとネストを深くすることもできます。


In [ ]:
d = [a,b,c]
d

[[1, 2, 3, 4, 5], ['Apple', 'Banana'], [1, 2, 3, 4, 5, 'Apple', 'Banana']]

In [ ]:
d[1]

['Apple', 'Banana']

```{note}
  - ネストされたリストからのデータ抽出は[1][1]などとします。

In [ ]:
d[1][1]

'Banana'

### リストの操作
- ```+```演算でリスト同士を足したり、```*```で複数にしたりすることができます。

In [25]:
a + b

NameError: name 'a' is not defined

In [26]:
b * 3

30

####  ミュータブルなリスト（一部、やや難）
- リストの中身は後から変更できます。これをミュータブルといいます。



In [ ]:
a

[1, 2, 3, 4, 5]

In [ ]:
a[0] = 2

In [ ]:
a

[2, 2, 3, 4, 5]

```{attention}
-  ミュータブルなデータ型を扱うときは代入の際に注意が必要です。
  - 例のようにbにaを代入した後、aの中身を変えるとbの中身も変わってしまいます。


In [27]:
#ミュータブルなリストのふるまい
a = [1, 2, 3, 4, 5]
b = a

In [28]:
b

[1, 2, 3, 4, 5]

In [29]:
a[0] = 2#aの中身を変えると。。

In [30]:
a

[2, 2, 3, 4, 5]

In [31]:
b

[2, 2, 3, 4, 5]

```{note}
- aの本当のコピーを作れば、このことは避けられます。[:]を使う方法とcopy()メソッドを使う方法があります。

In [ ]:
a = [1, 2, 3, 4, 5]
b = a[:]#b = a.copy()
a[0]=2 
b

[1, 2, 3, 4, 5]

### リストのメソッドと関数
- リストにも専用のメソッドがある。またリストによく使う関数もある。
```{list-table}
:header-rows: 1
* - 機能
  - メソッド・関数
* - 要約など
  - len(),sum()
* - 削除
  - del, remove() 
* - インデックス
  - index()
* - 付加、拡張
  - append(), extend()
* - 数える
  - count()
* - 要素の結合
  - join()
* - ソート
  - sort(), sorted()
```


#### len()関数とsum()関数
- len()関数はリストの長さを取得します。
- sum()関数は合計を返します。

In [2]:
a = [1, 2, 3, 4, 5]
len(a)

5

In [ ]:
len("Hello!")

6

In [ ]:
del(sum)

In [ ]:
a = [1, 2, 3, 4, 5]
sum(a)

15

#### del文とremove()メソッド
- リストの中身を削除するにはdel文を使います。インデックスを指定すると、該当要素が削除されます。
- あるいは要素が分かっているときは、remove()メソッドで削除することもできます。

In [ ]:
del a[2]
a

[1, 2, 4, 5]

In [ ]:
a.remove(5)
a

[1, 2, 4]

#### index()メソッド
- 要素のインデックスを知りたい場合はindex()を使います。

In [ ]:
a = [1, 2, 3, 4, 5]
a.index(2)

1

#### append()とextend()
- append()は要素を最後方から１つ追加します。
- for文と組み合わせて使うことが多いです。
  - リスト内包表記でよりシンプルに書ける（後述）

In [ ]:
a.append(6)
a

[1, 2, 3, 4, 5, 6]

In [ ]:
#1-100の整数から3の倍数をリストに格納
a = []
for i in range(1,101):
  if i % 3 == 0:
    a.append(i)
print(a)

[3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99]


- 複数追加したい場合は、extend()を使います(+演算子を使うこともできます)。
- append()を使うと、リストが要素として追加されるので注意。

In [3]:
a + [7,8,9]

[1, 2, 3, 4, 5, 7, 8, 9]

In [ ]:
a.extend([7,8,9])

In [4]:
a

[1, 2, 3, 4, 5]

In [ ]:
a.append([7,8,9])

In [ ]:
a

[3,
 6,
 9,
 12,
 15,
 18,
 21,
 24,
 27,
 30,
 33,
 36,
 39,
 42,
 45,
 48,
 51,
 54,
 57,
 60,
 63,
 66,
 69,
 72,
 75,
 78,
 81,
 84,
 87,
 90,
 93,
 96,
 99,
 7,
 8,
 9,
 [7, 8, 9]]

#### 数える。count()メソッド
- ある要素がリスト内にいくつあるかを調べるにはcount()メソッドを使います。

In [ ]:
a = [1,1,2,2,2,3]
a.count(2)

3

#### 文字列を要素とするリストの結合、join()メソッド
- " ".join([文字列の要素])とすると、要素が " "を間の区切りとしてつながる。

In [ ]:
mylist = ["apple","banana","orange","grape"]
" ".join(mylist)

'apple banana orange grape'

#### ソート
- リストを要素でソートするには、２つの方法があります。
- まずsort()メソッドを使う方法。この場合、リストの中身自体が変更されます。



In [ ]:
a = [5,3,1,2,4]
a.sort()
print(a)

[1, 2, 3, 4, 5]


- 関数sorted()を使う方法では、リストの中身は変更されず、返り値としてソートされたリストが返されます。

In [ ]:
a = [5,3,1,2,4]
sorted(a)

[1, 2, 3, 4, 5]

In [ ]:
a#aの中身は変わらない

[5, 3, 1, 2, 4]

```{important}
- 元のリストの中身を変える関数（メソッド）を「破壊的」、元のリストの中身を変えない関数（メソッド）を「非破壊的」といいます。
- 破壊的方法を使うと元に戻せなくなるので、単にソートしたいときなどには、非破壊的な方法を使って、別の変数に結果を保存するとよいでしょう。

In [ ]:
b = sorted(a)#ソート結果を別の変数に代入
print(b)

[1, 2, 3, 4, 5]


In [ ]:
print(a)

[5, 3, 1, 2, 4]


```{tip}
- 降順にしたい場合にはreverse=Trueとします。

In [ ]:
sorted(a, reverse=True)

[5, 4, 3, 2, 1]

## 問題4

#### 問題 4-1
与えられた文字列textからすべての空白を削除してください。


```
text = "This is a sample text."
```




In [187]:
text = "This is a sample text."
text.replace(" ","")

'Thisisasampletext.'

####問題4-2
与えられた文字列textを空白で分割し、単語のリストを作成してください。


```
text = "This is a sample text."
```




In [188]:
words = text.split(" ")
print(words)

['This', 'is', 'a', 'sample', 'text.']


####問題4-3


与えられた文字列textをカンマで分割し、それぞれの要素を大文字に変換して、新しいリストを作成してください。



```
text = "apple,banana,orange,grape"
```



In [190]:
text = "apple,banana,orange,grape"
words = text.split(",")
upper_words = []
for word in words:
  upper_words.append(word.upper())
print(upper_words)


['APPLE', 'BANANA', 'ORANGE', 'GRAPE']


問題4-4
- 次のリスト、["Spencer", "is", "dead."]を操作して、一つの文字列"Spencer is dead. "にせよ。

- 次の文字列、"Spencer is dead. But who killed him and how? This is the problem."、の'.'と'?'を削除したあと、小文字の単語を要素としたリストに変換せよ。
  - →のようにする['spencer', 'is', 'dead', 'but', 'who', 'killed', 'him', 'and', 'how', 'this', 'is', 'the', 'problem']



```
mylist = ["Spencer", "is", "dead."]
TP = "Spencer is dead. But who killed him and how? This is the problem."
```



In [191]:
mylist = ["Spencer", "is", "dead."]
TP = "Spencer is dead. But who killed him and how? This is the problem."
" ".join(mylist)

'Spencer is dead.'

In [192]:
TP.lower().replace(".","").replace("?", "").split(" ")

['spencer',
 'is',
 'dead',
 'but',
 'who',
 'killed',
 'him',
 'and',
 'how',
 'this',
 'is',
 'the',
 'problem']

## ディクショナリ
- ディクショナリは、keyとvalueからなり、マップ型と呼ばれる型に属する。
- {}でくくって、作成する。{key:value}と書く。


```{important}
- シーケンス型ではないのでインデックスは使えません。代わりにkeyを指定して要素を取り出します。要素は基本的にどのような型でもOKです。


In [194]:
d={'A':'Apple','B':'Banana'}

In [195]:
d['A']

'Apple'

```{note}
- ディクショナリもしばしばネストされます。

In [196]:
nested_d = {'nest':d}

In [198]:
nested_d['nest']

{'A': 'Apple', 'B': 'Banana'}

### ディクショナリ操作
- ディクショナリの場合、基本的な操作に工夫が必要となる場合があります。メソッドにこだわらず以下の基本的な操作について説明していきます。
    - 新しい項目を加える
    - 2つ以上の辞書を統合する
    - key, value, itemを取得する
    - ディクショナリのループ
    - ディクショナリのソート
    

#### ディクショナリに新しい項目を加える
- 空の辞書に新しい項目を加えるには、新しくkeyを指定してvalueを代入すればよい。


In [201]:
d = {}

In [202]:
d['ゲオルグ'] = 1858

In [203]:
d

{'ゲオルグ': 1858}

```{tip}
- もちろん既存の辞書に新しい項目を加えることもできます。


In [32]:
d = {'マックス':1864,'エミール':1858}
d['ゲオルグ'] = 1858
d

{'マックス': 1864, 'エミール': 1858, 'ゲオルグ': 1858}

#### ２つの辞書の統合：update()メソッド
- 2つの辞書を統合するにはupdate()メソッドを使います。

In [207]:
#新しい辞書を作り、
e = {'タルコット':1902,'ロバート':1910}
e

In [209]:
#先の辞書と統合する
d.update(e)
d

#### key, value, itemの取得
- それぞれ、keys(), values(), items()とすると取得できる。


In [210]:
d.keys()

dict_keys(['マックス', 'エミール', 'ゲオルグ', 'タルコット', 'ロバート'])

In [211]:
'ガブリエル' in d.keys()

False

In [212]:
d.values()

dict_values([1864, 1858, 1858, 1902, 1910])

```{important}
- items()はkeyとvalueのタプルを要素とするリスト形式のオブジェクトを返します。

In [213]:
d.items()

dict_items([('マックス', 1864), ('エミール', 1858), ('ゲオルグ', 1858), ('タルコット', 1902), ('ロバート', 1910)])

#### get()メソッドによるvalueの取得
- ディクショナリのvalueはkeyを指定して取れるが、keyが存在しない場合はエラーが出る。


In [214]:
d['マックス']

1864

```{error}
- 問い合わせたkeyが存在しない場合エラーが出る

In [215]:
d['ガブリエル']

KeyError: ignored

```{tip}
- get()メソッドを使うと、keyが存在すればvalueを返し、存在しなければ何も返さない（Noneを返す)ということができます。

In [216]:
if d.get('マックス'):
    print(d['マックス'])

1864


In [217]:
if d.get('ガブリエル'):
    print(d['ガブリエル'])
else:
    print('そのkeyは存在しません')

そのkeyは存在しません


```{note}
- このようにifの条件節はNoneだとFalse、それ以外はTrueを返します。

#### ディクショナリのループ
- ディクショナリの中身をループするときには、d.items()を使って、key, valueのペアをループします。

In [33]:
d.items()

dict_items([('マックス', 1864), ('エミール', 1858), ('ゲオルグ', 1858)])

In [34]:
for key, value in d.items():
    print(f'{key}:{value}')

マックス:1864
エミール:1858
ゲオルグ:1858


```{note}
- このようにfor文のinの前の項目は複数でもOKです。

#### ディクショナリのソート
- ディクショナリをvalueでソートしたい場合は一工夫必要です。sorted()を使えますが、ソートのkey（ディクショナリのkeyではない）として、lambda関数というやり方を使い、ディクショナリのvalueをソートのkeyとすると指定します。


In [223]:
sorted(d.items(), key = lambda x : x[1])

[('エミール', 1858),
 ('ゲオルグ', 1858),
 ('マックス', 1864),
 ('タルコット', 1902),
 ('ロバート', 1910)]

## 問題5


####問題5-1
空の辞書gradesを作成し、次のキーと値のペアを追加してください。

'math': 85
'science': 90
'english': 88

In [224]:
grades = {}
grades['math'] = 85
grades['science'] = 90
grades['english'] = 88
grades

#### 問題5-2
与えられた辞書studentのキーと値をイテレートし、次の形式で出力してください

key: value


```
student = {'name': 'John', 'age': 21, 'major': 'Computer Science'}
```



In [226]:
student = {'name': 'John', 'age': 21, 'major': 'Computer Science'}
for key, value in student.items():
  print(f'{key}:{value}')

name:John
age:21
major:Computer Science


#### 問題5-3
与えられた辞書pricesのすべての値の合計を計算してください。



```
prices = {'apple': 1.5, 'banana': 0.5, 'orange': 0.75}
```



In [227]:
prices = {'apple': 1.5, 'banana': 0.5, 'orange': 0.75}
sum(prices.values())

2.75

####問題5-4
5-1で作成したgradeを値でソートしてください。


In [228]:
sorted(grades.items(), key = lambda x: x[1])

[('math', 85), ('english', 88), ('science', 90)]

##  タプル
- リストに似ていますが、イミュータブルであるという点で異なります。不用意に要素が変更されることがないのでリストよりも安全です。
- ()でくくって作ります。


In [229]:
t=(1,2,3,4,5)

 ```{error}
 - リストのように要素に代入しようとするとエラーが発生します。

In [230]:
t[0] = 5

TypeError: ignored

## モジュール（ライブラリ）
- Pythonにはモジュールと呼ばれるプログラムパッケージが多数存在します。
-  モジュールは以下に区別できます。
  - 1)Pythonにあらかじめ組み込まれているもの
  - 2)Colabに最初から入っているもの
  - 3)その他、別個インストールが必要となるもの
     - 3)については、pip install, conda installなどとして別個インストールが必要になります。

```{important}
- モジュールを読み込むときは"import XX"とする。"import XX as Y"とすると、Yという名前で使うことができる。

In [233]:
import random
random.choice([1,2,3,4,5,6])

5

In [234]:
import pandas as pd
pd.DataFrame({"A":[1,2],"B":[3,4]})

A  B
0  1  3
1  2  4

## いろいろなプログラミングテクニック

#### forloopの進んだ使い方。enumerateとzip
- リストをループしているときにそのインデックスもあわせて取得したい場合があります。
- enumerate()を使ってループすると、インデックスと要素を使ってループすることができます。

In [235]:
l = ['エミール', 'ゲオルグ','マックス', 'タルコット', 'ロバート']
for idx, name in enumerate(l):
    print("私（{}）のインデックスは{}番です".format(name,idx))

私（エミール）のインデックスは0番です
私（ゲオルグ）のインデックスは1番です
私（マックス）のインデックスは2番です
私（タルコット）のインデックスは3番です
私（ロバート）のインデックスは4番です


- zip()を使うとペアごとにループできます。

In [236]:
l = ['エミール', 'ゲオルグ','マックス', 'タルコット', 'ロバート']
m = ['デュルケム','ジンメル','ウェーバー','パーソンズ','マートン']
for first,last in zip(l,m):
    print("私は{}・{}です".format(first,last))

私はエミール・デュルケムです
私はゲオルグ・ジンメルです
私はマックス・ウェーバーです
私はタルコット・パーソンズです
私はロバート・マートンです


#### リスト内包表記

- [item for item in list]のような形でリストの内部でfor文を使う方法です。pythonプログラミングで非常によく使われます。


In [237]:
nums = [2, 4, 5, 6, 8, 10, 12]
new_nums = [num // 2 for num in nums]
print(new_nums)


[1, 2, 2, 3, 4, 5, 6]


```{important}
- さらにifで条件付けることができます。
  - ifのみの場合はforの後にifをおきます。


In [238]:
nums = [2, 4, 5, 6, 8, 10, 12]
new_nums = [num // 2 for num in nums if num > 5]
print(new_nums)


[3, 4, 5, 6]


```{important}
- if else で条件付けるときはforの前にif...else をおきます。

In [240]:
nums = [2, 4, 5, 6, 8, 10, 12]
new_nums = [num // 2 if num > 5 else num for num in nums]
print(new_nums)


[2, 4, 5, 3, 4, 5, 6]


- 使用例を見てみます。

In [35]:
d = {'マックス': 1864, 'エミール': 1858, 'ゲオルグ': 1858, 'タルコット': 1902, 'ロバート': 1910}
statement = [f"私（{key}）の誕生年は{value}年です" for key, value  in d.items()]
statement

['私（マックス）の誕生年は1864年です',
 '私（エミール）の誕生年は1858年です',
 '私（ゲオルグ）の誕生年は1858年です',
 '私（タルコット）の誕生年は1902年です',
 '私（ロバート）の誕生年は1910年です']

In [36]:
[f"私（{key}）の誕生年は{value}年です" for key, value  in d.items() if int(value) >1900]

['私（タルコット）の誕生年は1902年です', '私（ロバート）の誕生年は1910年です']

In [37]:
[f"私（{key}）の誕生年は{value}年です" if int(value) >1900 else "" for key, value  in d.items() ]

['', '', '', '私（タルコット）の誕生年は1902年です', '私（ロバート）の誕生年は1910年です']

## 問題6



#### 問題6-1
与えられたリストnumsの各要素の値とそのインデックスを掛けた新しいリストを、リスト内包表記とenumerateを用いて作成してください。



In [244]:
nums = [1,2,3,4,5]

In [247]:
[num * index for index, num in enumerate(nums)]

[0, 2, 6, 12, 20]

#### 問題6-2
与えられたリストnamesとagesを使って、"{name} is {age} years old"という形式の文字列のリストを作成してください。zipを用いてください。



In [245]:
names = ["Alice", "Bob", "Carol"]
ages = [25, 30, 35]


In [248]:
[f"{name} is {age} years old" for name, age in zip(names,ages)]

['Alice is 25 years old', 'Bob is 30 years old', 'Carol is 35 years old']

### 問題6-3
与えられたリストvaluesの各要素について、インデックスが偶数の要素は2倍し、インデックスが奇数の要素は3倍した新しいリストを作成してください。リスト内包表記とenumerateを用いてください。



In [246]:
values = [1,2,3,4,5]

In [250]:
[value*2 if index % 2 ==0 else value*3 for index, value in enumerate(values)]

[2, 6, 6, 12, 10]

## numpyについて
- numpyは数値計算用に開発された非常にポピュラーなモジュールです。数学的処理をする場合に不可欠なだけでなく、後で出てくるpandasなどのデータ処理用のモジュールはこのnumpyの機能を基礎にして組み立てられています。numpyを使うと、通常の方法よりも処理速度を大幅に上げることもできます。ここではそのさわりの部分だけを紹介します。


In [1]:
import numpy as np

### numpy配列
- numpyの基本は配列(array)です。リストに似ていますが、同じ型の要素しか取れないなどいくつかの違いがあります。
- 配列はnp.array([])によって作ることができます。これは数学的にはベクトルに相当します。

In [3]:
vec = np.array([1,2,3])
vec

array([1, 2, 3])

```{important}
- 2次元配列も作ることができます。数学的には行列にあたります。


In [4]:
mat = np.array([
              [1,2,3],
              [4,5,6],
              [7,8,9]
                ])
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
mat2 = np.array([
              [10,20,30],
              [40,50,60],
              [70,80,90]
                ])
mat2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

```{important}
- ベクトルや行列として演算したいときにはnp.dot()などを用います。

In [6]:
np.dot(mat,mat2)#1*10+2*40+3*70=300,...

array([[ 300,  360,  420],
       [ 660,  810,  960],
       [1020, 1260, 1500]])

### アダマール積とブロードキャスト
- '*'演算子は要素ごとのかけ算をかえします。これをアダマール積といいます。


In [8]:
mat*mat2#アダマール積1*10,...

array([[ 10,  40,  90],
       [160, 250, 360],
       [490, 640, 810]])

```{important}
- かけ算する行列同士の次元が異なる場合、ブロードキャストが行われる。簡単にいえば、次元が少ない方のオブジェクトを複数コピーして次元を合わせて演算する。

In [9]:
vec

array([1, 2, 3])

In [10]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
mat * vec

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

### インデックスによる選択
- インデックスによる選択はリスト等に似ていますが、リストで選択する機能が追加されています。

In [12]:
mat[:2,1]

array([2, 5])

```{important}
- リストを使えば、インデックスを飛ばして複数を選択できます。

In [13]:
mat[[0,2],:]

array([[1, 2, 3],
       [7, 8, 9]])

#### 零行列、単位行列など
- np.zeros()を使うと、ゼロからなる行列を作ることができます。


In [14]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

- np.eye()は単位行列を作ります。


In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

- その他、np.ones()など類似の関数もいくつか用意されています。

In [16]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 数学関数とapply
- np.sum()やnp.mean()などの多くの数学関数が用意されています。


In [17]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
np.mean(mat)

5.0

In [19]:
np.sum(mat)

45

```{note}
- np.apply_along_axis()を使うと行ごとや列ごとに数学関数を適用できます。

In [20]:
np.apply_along_axis(np.sum, 1, mat)#行の足し算

array([ 6, 15, 24])

In [21]:
np.apply_along_axis(np.sum, 0, mat)#列の足し算

array([12, 15, 18])

## Colabのディレクトリ構造とLinuxコマンド
- Colabはクラウド上のLinuxコンピュータで、図のようなディレクトリ（Winでいうフォルダに相当）構造を持っています。

<img src="https://raw.githubusercontent.com/berutaki/github.io/main/1-5.png" width="300">

- (Colab)から見て外部ドライブ（各自のグーグルドライブ）を接続するにはマウントをする必要があります。

- マウントの場所を''/content/drive'と指定するとcontentディレクトリの直下にMy diriveが接続されます。

<img src="https://raw.githubusercontent.com/berutaki/github.io/main/1-6.png" width="300">



In [264]:
from google.colab import drive
drive.mount('/content/drive')#実行すると許可を求められるが、すべてOKする。

Mounted at /content/drive


### Linuxコマンド
- Colabでは'!'を頭につけることでLinuxのコマンドを入力できます（ただし、サブプロセスで実行されるため意図した動作をできないこともある）。
- '%'はIPythonのマジックコマンドで'!'と同じようなことができます（pipなどは不可）。以下では基本的に'%'を使います（実は何もつけなくても以下のコマンドは動く）。
- 'pwd'は現在のワーキングディレクトリを表示。


In [265]:
!pwd

/content


In [266]:
%pwd

'/content'

- 'cd'はディレクトリの移動。


In [ ]:
%cd /content/drive/MyDrive/cssws2023

/content/drive/MyDrive/cssws2023


- 'ls'はディレクトリやファイルのリストの表示

In [267]:
%ls

drive/  sample_data/


- 'mkdir'はディレクトリの作成


In [275]:
%mkdir test

In [276]:
%ls#testというフォルダができている

data/                         test/
kokkai_data.ipynb             Todai_pandas.ipynb
kokkai_simple_analysis.ipynb  Todai_pandas配布用.ipynb
kokkai_tokenize.ipynb         Todai_Python_Basics.ipynb
kokkai_topic.ipynb            Todai_Python_Basics配布用.ipynb
mecab-ipadic-neologd/         問題（回答付き）.ipynb


- 'rm -r'はディレクトリの削除

In [277]:
%rm -r test

In [22]:
%ls#testが消えている

UsageError: Line magic function `%ls#testが消えている` not found.


#### パスとcd
- 絶対パスと相対パス
  - 絶対パス：/content/drive/MyDrive/cssws2023は絶対パスでディレクトリやファイルの場所を示す住所のこと。
  - 相対パス：カレントディレクトリから見た場所を示す。例えば、MyDriveにいるときに上の場所（/content/drive/MyDrive/cssws2023）を相対パスで表せば /cssws2023 となる。

```{tip}
- 'cd ..'はカレントディレクトリの一つ前のディレクトリへいく。
- ' cd -'は直前にいたディレクトリに戻る。
- 'cd ~'はhomeに戻る（Colabでは/root）

In [282]:
%cd /content/drive

/content/drive


In [283]:
%cd MyDrive/cssws2023

/content/drive/MyDrive/cssws2023


In [284]:
%cd ..#cssws2023からMyDriveに戻る

/content/drive/MyDrive


In [285]:
%cd -#直前のディレクトリに戻る

/content/drive/MyDrive/cssws2023


In [286]:
%cd ~#ホームディレクトリに戻る

/root


In [ ]:
%pwd#ホームディレクトリに戻っている

'/content/drive/MyDrive/cssws2023'

### osによるディレクトリ、ファイルの操作
- osライブラリでディレクトリやファイルを操作すると便利なことがあります。
- mkdir()でディレクトリを作る。

In [288]:
import os
os.mkdir('test')

In [289]:
%ls

data/                         test/
kokkai_data.ipynb             Todai_pandas.ipynb
kokkai_simple_analysis.ipynb  Todai_pandas配布用.ipynb
kokkai_tokenize.ipynb         Todai_Python_Basics.ipynb
kokkai_topic.ipynb            Todai_Python_Basics配布用.ipynb
mecab-ipadic-neologd/         問題（回答付き）.ipynb


- os.path.exists()とすると、当該ファイルが存在するかどうかを確認できます。

In [290]:
os.path.exists('test')

True

- os.path.exists('test')で確かめてなければ作る。


In [291]:
if not os.path.exists('test2'):
  os.mkdir('test2')

- 練習用に空のファイルを作っておきます。

In [292]:
#操作練習用テキストファイル
with open ('text1.txt','w') as f:
  pass
with open ('text2.txt','w') as f:
  pass

In [293]:
ls

data/                         text1.txt
kokkai_data.ipynb             text2.txt
kokkai_simple_analysis.ipynb  Todai_pandas.ipynb
kokkai_tokenize.ipynb         Todai_pandas配布用.ipynb
kokkai_topic.ipynb            Todai_Python_Basics.ipynb
mecab-ipadic-neologd/         Todai_Python_Basics配布用.ipynb
test/                         問題（回答付き）.ipynb
test2/


- os.listdir()でディレクトリ内のファイルを取得。


In [294]:
my_listdir = os.listdir()
print(my_listdir)

['問題（回答付き）.ipynb', 'data', 'mecab-ipadic-neologd', 'kokkai_topic.ipynb', 'kokkai_data.ipynb', 'Todai_pandas配布用.ipynb', 'kokkai_simple_analysis.ipynb', 'kokkai_tokenize.ipynb', 'Todai_pandas.ipynb', 'Todai_Python_Basics.ipynb', 'Todai_Python_Basics配布用.ipynb', 'test', 'test2', 'text1.txt', 'text2.txt']


```{important}
- osを使ってもよいのですが。。
- globライブラリを使うと条件を指定してファイルを取得できます。


In [296]:
import glob
glob.glob('*.ipynb')

['問題（回答付き）.ipynb',
 'kokkai_topic.ipynb',
 'kokkai_data.ipynb',
 'Todai_pandas配布用.ipynb',
 'kokkai_simple_analysis.ipynb',
 'kokkai_tokenize.ipynb',
 'Todai_pandas.ipynb',
 'Todai_Python_Basics.ipynb',
 'Todai_Python_Basics配布用.ipynb']

- os.remove()でファイルを消す。


In [297]:
os.remove('text1.txt')
os.remove('text2.txt')

```{tip}
-  ディレクトリを消すには、shutilライブラリのrmtree()を使う。

In [298]:
import shutil
shutil.rmtree('test')
shutil.rmtree('test2')

In [23]:
os.listdir()#ファイルが消えている

NameError: name 'os' is not defined

## ファイルインプット／アウトプット
- Pythonではいろいろな方法で外部のファイルを読み込んだり、外部にファイルを出力することができます。
  - with open()を使う方法
  - csvモジュールを使う方法
  - pandasを使う方法
  - pickleを使う方法



### open()による書き込み
- with open('hoge.hoge','w') as f:とすると、ファイルオブジェクトfを'w'書き込みモードで作り、'hoge.hoge'に書き込む。

In [300]:
d = {'マックス': 1864, 'エミール': 1858, 'ゲオルグ': 1858, 'タルコット': 1902, 'ロバート': 1910}#書き込み練習用の辞書を作成


- withを使います。

In [301]:
with open('sample.csv','w') as f:
  for key, value in d.items():
    f.write(f"{key},{value}\n")

In [302]:
%ls#sample.csvができている

data/                         sample.csv
kokkai_data.ipynb             Todai_pandas.ipynb
kokkai_simple_analysis.ipynb  Todai_pandas配布用.ipynb
kokkai_tokenize.ipynb         Todai_Python_Basics.ipynb
kokkai_topic.ipynb            Todai_Python_Basics配布用.ipynb
mecab-ipadic-neologd/         問題（回答付き）.ipynb


In [303]:
%cat sample.csv#中身を確認

マックス,1864
エミール,1858
ゲオルグ,1858
タルコット,1902
ロバート,1910


- withを使わずにも書けますが、ファイルオブジェクトをクローズする必要があります。
  - hoge.close()とします。


In [ ]:
f = open('sample.csv','w')
for key, value in d.items():
  f.write(f"{key},{value}\n")
f.close()


In [24]:
%cat sample.csv#中身を確認

cat: sample.csv#中身を確認: No such file or directory


- 'a'で開くと上書きモードとなる。

In [304]:
with open('sample.csv','a') as f:
  key = "ニクラス"
  value =  1927
  f.write(f"{key},{value}\n")

In [305]:
%cat sample.csv#中身を確認

マックス,1864
エミール,1858
ゲオルグ,1858
タルコット,1902
ロバート,1910
ニクラス,1927


### open()による読み込み
- open()を使って"r"読み込みモードで開く。


```{important}

- Windowsでは文字コードが異なるので、encoding = 'utf-8'とする。


```{important}
- 読み込みのメソッドは複数会ってそれぞれ挙動が異なるので注意してください。
- read()
- readlines()
- readline()

- read()メソッドでは、ファイルが一つの文字列として読みこまれる。


In [306]:
with open('sample.csv','r',encoding = 'utf-8') as f:
  sample = f.read()
sample

'マックス,1864\nエミール,1858\nゲオルグ,1858\nタルコット,1902\nロバート,1910\nニクラス,1927\n'

- readlines()は改行コード(\n)で区切ったリストを返す。


In [307]:
with open('sample.csv','r',encoding = 'utf-8') as f:
  sample = f.readlines()
sample

['マックス,1864\n',
 'エミール,1858\n',
 'ゲオルグ,1858\n',
 'タルコット,1902\n',
 'ロバート,1910\n',
 'ニクラス,1927\n']

- readline()はファイルを一行ずつ呼んでいきます。
  - whileの無限ループを使って次々に呼び出していき、最後まで読むと、空の文字列を返すので、if notで条件づけてbreakで無限ループを脱出する。


```{note}注意
- ファイルオブジェクトは１回呼び出すと中身が更新される（例えば、f.read()をすると、fの中身は空になります。）
```

In [308]:
with open('sample.csv','r',encoding = 'utf-8') as f:
  while True:#一行ずつ読み込んでいき、空になったらbreak
      line = f.readline()
      print(line)
      if not line:
          break

マックス,1864

エミール,1858

ゲオルグ,1858

タルコット,1902

ロバート,1910

ニクラス,1927




#### csvによる書き込み
- csv.writer()で書き込み用オブジェクトを作成します。

```{important}
- 書き込みのメソッドもwriterow(), writerows()の区別があります。

- writerow()メソッドを用いて、一行ずつ書き込む。


In [310]:
sample = [['マックス','1864'], ['エミール', '1858'], ['ゲオルグ', '1858']]
import csv
with open('sample.csv','w') as f:
    writer = csv.writer(f)
    for row in sample:
        writer.writerow(row)

In [311]:
%cat sample.csv

マックス,1864
エミール,1858
ゲオルグ,1858


- wroterows()は二次元リストを一気に書き込む。


In [312]:
with open('sample.csv','w') as f:
    writer = csv.writer(f)
    writer.writerows(sample)
 

In [313]:
%cat sample.csv

マックス,1864
エミール,1858
ゲオルグ,1858


### csvによる読み込み
- reader()メソッドでファイルを読み込む。
- for文で一行ずつ取り出す。


In [314]:
sample = []
with open('sample.csv','r') as f:
    reader = csv.reader(f)
    #print(type(reader))
    for item in reader:
        sample.append(item)
sample

[['マックス', '1864'], ['エミール', '1858'], ['ゲオルグ', '1858']]

```{note}
- csv.reader()で作られたreaderオブジェクトはイテレータと呼ばれるオブジェクトで、for 文で一個ずつ繰り返し呼び出して中身を取り出すことができる。

#### pandasで読み書きする。
- pandasのread_csv()メソッドを使うことでcsvをデータフレームとして読み込むことができる。


In [315]:
import pandas as pd

In [316]:
dat = pd.read_csv('sample.csv', header = None)

In [317]:
dat.head()

0     1
0  マックス  1864
1  エミール  1858
2  ゲオルグ  1858

- to_csv()メソッドでデータフレームをcsvとして書き込むことができる。

In [318]:
dat.to_csv('sample.csv',index = False, header = False)

In [319]:
%cat sample.csv

マックス,1864
エミール,1858
ゲオルグ,1858


### pickleで読み書きする
- pickleはPythonオブジェクトのままバイナリ形式で保存し、読み込む。処理がPythonのみで完結している際は推奨。

```{note}
- pickleを使う場合には、with open()を用います。
- 'wb'はバイナリオブジェクトの書き込み
- 'rb'はバイナリオブジェクトの読み込み

- 書き込みはpickle.dump()を使う。


In [320]:
sample = [['マックス','1864'], ['エミール', '1858'], ['ゲオルグ', '1858']]

import pickle
with open ('sample.pickle','wb') as f:#バイナリオブジェクトなので'w'ではなく'wb'とする。
  pickle.dump(sample,f)

In [321]:
%ls

data/                         sample.pickle
kokkai_data.ipynb             Todai_pandas.ipynb
kokkai_simple_analysis.ipynb  Todai_pandas配布用.ipynb
kokkai_tokenize.ipynb         Todai_Python_Basics.ipynb
kokkai_topic.ipynb            Todai_Python_Basics配布用.ipynb
mecab-ipadic-neologd/         問題（回答付き）.ipynb
sample.csv


In [322]:
%cat sample.pickle

��N]�(]�(�マックス��1864�e]�(�エミール��1858�e]�(�ゲオルグ�hee.

- 読み込みはpickle.load()を使う。

In [323]:
with open ('sample.pickle','rb') as f:#バイナリオブジェクトなので'r'ではなく'rb'とする。
  sample = pickle.load(f)

In [324]:
sample

[['マックス', '1864'], ['エミール', '1858'], ['ゲオルグ', '1858']]